/* See COPYRIGHT for copyright information. */

#include <inc/x86.h>
#include <inc/mmu.h>
#include <inc/error.h>
#include <inc/string.h>
#include <inc/assert.h>

#include <kern/pmap.h>
#include <kern/kclock.h>

// These variables are set by i386_detect_memory()
size_t npages;			// Amount of physical memory (in pages)
static size_t npages_basemem;	// Amount of base memory (in pages)

// These variables are set in mem_init()
pml4e_t *kern_pml4;		// Kernel's initial page directory
struct PageInfo *pages;		// Physical page state array
static struct PageInfo *page_free_list;	// Free list of physical pages


// --------------------------------------------------------------
// Detect machine's physical memory setup.
// --------------------------------------------------------------

static int
nvram_read(int r)
{
	return mc146818_read(r) | (mc146818_read(r + 1) << 8);
}

static void
i386_detect_memory(void)
{
	size_t basemem, extmem, ext16mem, totalmem;

	// Use CMOS calls to measure available base & extended memory.
	// (CMOS calls return results in kilobytes.)
	basemem = nvram_read(NVRAM_BASELO);
	extmem = nvram_read(NVRAM_EXTLO);
	ext16mem = nvram_read(NVRAM_EXT16LO) * 64;

	// Calculate the number of physical pages available in both base
	// and extended memory.
	if (ext16mem)
		totalmem = 16 * 1024 + ext16mem;
	else if (extmem)
		totalmem = 1 * 1024 + extmem;
	else
		totalmem = basemem;

	npages = totalmem / (PGSIZE / 1024);
	npages_basemem = basemem / (PGSIZE / 1024);

	cprintf("Physical memory: %uK available, base = %uK, extended = %uK\n",
		totalmem, basemem, totalmem - basemem);
}


// --------------------------------------------------------------
// Set up memory mappings above UTOP.
// --------------------------------------------------------------

static void boot_map_region(pml4e_t *pml4e, uintptr_t va, size_t size, physaddr_t pa, int perm);
static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_kern_pml4e(void);
static physaddr_t check_va2pa(pml4e_t *pml4e, uintptr_t va);
static void check_page(void);
static void check_page_installed_pml4e(void);

// This simple physical memory allocator is used only while JOS is setting
// up its virtual memory system.  page_alloc() is the real allocator.
//
// If n>0, allocates enough pages of contiguous physical memory to hold 'n'
// bytes.  Doesn't initialize the memory.  Returns a kernel virtual address.
//
// If n==0, returns the address of the next free page without allocating
// anything.
//
// If we're out of memory, boot_alloc should panic.
// This function may ONLY be used during initialization,
// before the page_free_list list has been set up.
//
// boot_alloc INVARIANT that we must maintain is:
// 	The physical page whose kernel-virtual addresses start at nextfree and above remain free for allocation
static void *
boot_alloc(uint32_t n)
{
	static char *nextfree;	// virtual address of next byte of free memory.
	char *prev_nextfree;
	char *result;

	// Initialize nextfree if this is the first time.
	// 'end' is a magic symbol automatically generated by the linker,
	// which points to the end of the kernel's bss segment:
	// the first virtual address that the linker did *not* assign
	// to any kernel code or global variables.
	if (!nextfree) {
		extern char end[];
		nextfree = ROUNDUP((char *) end, PGSIZE);
	}

	// Allocate a chunk large enough to hold 'n' bytes, then update
	// nextfree.  Make sure nextfree is kept aligned
	// to a multiple of PGSIZE.
	//
	// LAB 2: Your code here.
	if (n == 0) {
        return nextfree;
    }
    
    result = nextfree;
    
    nextfree = ROUNDUP(nextfree + n, PGSIZE);
    
    if (PADDR(nextfree) > npages * PGSIZE) {
        panic("boot_alloc: out of memory");
    }
    
	// create pages:
	// an array of 'struct Pageinfo' records. The pages array has npages records



    return result;
}

// Set up a two-level page table:
//    kern_pgdir is its linear (virtual) address of the root
//
// This function only sets up the kernel part of the address space
// (ie. addresses >= UTOP).  The user part of the address space
// will be set up later.
//
// From UTOP to ULIM, the user is allowed to read but not write.
// Above ULIM the user cannot read or write.
void
mem_init(void)
{
	uint32_t cr0;
	size_t n;

	// Find out how much memory the machine has (npages & npages_basemem).
	i386_detect_memory();

	//////////////////////////////////////////////////////////////////////
	// create initial page directory.
	kern_pml4 = (pml4e_t *) boot_alloc(PGSIZE);
	memset(kern_pml4, 0, PGSIZE);

	//////////////////////////////////////////////////////////////////////
	// Recursively insert PD in itself as a page table, to form
	// a virtual page table at virtual address UVPT.
	// (For now, you don't have understand the greater purpose of the
	// following line.)

	// Permissions: kernel R, user R
	kern_pml4[PML4X(UVPT)] = PADDR(kern_pml4) | PTE_U | PTE_P;

	//////////////////////////////////////////////////////////////////////
	// Allocate an array of npages 'struct PageInfo's and store it in 'pages'.
	// The kernel uses this array to keep track of physical pages: for
	// each physical page, there is a corresponding struct PageInfo in this
	// array.  'npages' is the number of physical pages in memory.  Use memset
	// to initialize all fields of each struct PageInfo to 0.
	// Your code goes here:

	pages = (struct PageInfo *) boot_alloc(npages * sizeof(struct PageInfo));
	memset(pages, 0, npages * sizeof(struct PageInfo));

	//////////////////////////////////////////////////////////////////////
	// Now that we've allocated the initial kernel data structures, we set
	// up the list of free physical pages. Once we've done so, all further
	// memory management will go through the page_* functions. In
	// particular, we can now map memory using boot_map_region
	// or page_insert
	page_init();

	// if these tests arent done here, pages at the end of memory not 
	// currently mapped are used and crash the system
	check_page_free_list(1);
	check_page_alloc();
	check_page();


	//////////////////////////////////////////////////////////////////////
	// Now we set up virtual memory

	//////////////////////////////////////////////////////////////////////
	// Map 'pages' read-only by the user at linear address UPAGES
	// Permissions:
	//    - the new image at UPAGES -- kernel R, user R
	//      (ie. perm = PTE_U | PTE_P)
	//    - pages itself -- kernel RW, user NONE
	// Your code goes here:

	boot_map_region(kern_pml4, 
                UPAGES, 
                ROUNDUP(npages * sizeof(struct PageInfo), PGSIZE), 
                PADDR(pages), 
                PTE_U | PTE_P);

	//////////////////////////////////////////////////////////////////////
	// Use the physical memory that 'bootstack' refers to as the kernel
	// stack.  The kernel stack grows down from virtual address KSTACKTOP.
	// We consider the entire range from [KSTACKTOP-PTSIZE, KSTACKTOP)
	// to be the kernel stack, but break this into two pieces:
	//     * [KSTACKTOP-KSTKSIZE, KSTACKTOP) -- backed by physical memory
	//     * [KSTACKTOP-PTSIZE, KSTACKTOP-KSTKSIZE) -- not backed; so if
	//       the kernel overflows its stack, it will fault rather than
	//       overwrite memory.  Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	// Your code goes here:
	boot_map_region(kern_pml4,
                KSTACKTOP - KSTKSIZE,
                KSTKSIZE,
                PADDR(bootstack),
                PTE_W | PTE_P);


	//////////////////////////////////////////////////////////////////////
	// Map all of physical memory at KERNBASE.
	// Ie.  the VA range [KERNBASE, 2^32) should map to
	//      the PA range [0, 2^32 - KERNBASE)
	// We might not have 2^32 - KERNBASE bytes of physical memory, but
	// we just set up the mapping anyway.
	// Permissions: kernel RW, user NONE
	// Your code goes here:

	boot_map_region(kern_pml4,
                KERNBASE,
                (1ULL << 32) - KERNBASE,   // Full range: 2^32 - KERNBASE
                0,
                PTE_W | PTE_P);


	// Check that the initial page directory has been set up correctly.
	check_kern_pml4e();

	// Switch from the minimal entry page directory to the full kern_pgdir
	// page table we just created.	Our instruction pointer should be
	// somewhere between KERNBASE and KERNBASE+4MB right now, which is
	// mapped the same way by both page tables.
	//
	// If the machine reboots at this point, you've probably set up your
	// kern_pgdir wrong.
	pdpe_t *pdpe = KADDR(PTE_ADDR(kern_pml4[PML4X(KERNBASE)]));
	pde_t *pgdir = KADDR(PTE_ADDR(pdpe[PDPX(KERNBASE)]));



	lcr3(PADDR(kern_pml4));

	check_page_free_list(0);

	// entry.S set the really important flags in cr0 (including enabling
	// paging).  Here we configure the rest of the flags that we care about.
	// cr0 = rcr0();
	// cr0 |= CR0_PE|CR0_PG|CR0_AM|CR0_WP|CR0_NE|CR0_MP;
	// cr0 &= ~(CR0_TS|CR0_EM);
	// lcr0(cr0);

	// Some more checks, only possible after kern_pgdir is installed.
	check_page_installed_pml4e();

	///todo fix
}

// --------------------------------------------------------------
// Tracking of physical pages.
// The 'pages' array has one 'struct PageInfo' entry per physical page.
// Pages are reference counted, and free pages are kept on a linked list.
// --------------------------------------------------------------

//
// Initialize page structure and memory free list.
// After this is done, NEVER use boot_alloc again.  ONLY use the page
// allocator functions below to allocate and deallocate physical
// memory via the page_free_list.
//
void
page_init(void)
{
	// The example code here marks all physical pages as free.
	// However this is not truly the case.  What memory is free?
	//  1) Mark physical page 0 as in use.
	//     This way we preserve the real-mode IDT and BIOS structures
	//     in case we ever need them.  (Currently we don't, but...)
	//  2) The rest of base memory, [PGSIZE, npages_basemem * PGSIZE)
	//     is free.
	//  3) Then comes the IO hole [IOPHYSMEM, EXTPHYSMEM), which must
	//     never be allocated.
	//  4) Then extended memory [EXTPHYSMEM, ...).
	//     Some of it is in use, some is free. Where is the kernel
	//     in physical memory?  Which pages are already in use for
	//     page tables and other data structures?
	//
	// Change the code to reflect this.
	// NB: DO NOT actually touch the physical memory corresponding to
	// free pages!

	/*
	notes for page_init:
	- Construct list by inserting new nodes at head of linked list
	- Start with: page_free_list = NULL
	- Add all free pages in the array with a loop

	Predicament: pp_ref can be checked to see if a page is free or not, but mem_init just filled the whole pages array with zero
	even if some are being used. 
	Solution: check data of first byte maybe? Or can I check if the page has a physical address? or maybe use nextfree somehow?

	Regardless, at end of page_init:
	- page_free_list must contain all pages from 1 to end of basemem
	- also contain pages beginning at nextfree to last available page

	*/
	size_t i;
	physaddr_t first_free_addr = PADDR(boot_alloc(0));
    size_t first_free_page = first_free_addr / PGSIZE;
	page_free_list = NULL;

	for (i = 0; i < npages; i++) {
		// Page 0 - in use (BIOS/IDT)
        if (i == 0) {
            pages[i].pp_ref = 1;
            pages[i]. pp_link = NULL;
            continue;
        }
        
        // base memory [1, npages_basemem) - FREE
        if (i >= 1 && i < npages_basemem) {
            pages[i].pp_ref = 0;
            pages[i]. pp_link = page_free_list;
            page_free_list = &pages[i];
            continue;
        }
        
        // I/O hole [IOPHYSMEM, EXTPHYSMEM) - in use
        if (i >= IOPHYSMEM / PGSIZE && i < EXTPHYSMEM / PGSIZE) {
            pages[i].pp_ref = 1;
            pages[i].pp_link = NULL;
            continue;
        }
        
       // [EXTPHYSMEM, first_free_addr) - in use (kernel, page tables, pages[])
        if (i >= EXTPHYSMEM / PGSIZE && i < first_free_page) {
            pages[i].pp_ref = 1;
            pages[i].pp_link = NULL;
            continue;
        }
        
        // [first_free_addr, end of memory) - FREE
        if (i >= first_free_page) {
            pages[i].pp_ref = 0;
            pages[i]. pp_link = page_free_list;
            page_free_list = &pages[i];
        }
	}
}

/*
- returns 'struct PageInfo' record of a free page from page_free_list
- That record must be detached from the list and its corresponding page should be zero-filled if caller passed ALLOC_ZERO
- Check that page_free_list has pages; if empty return null
- select furst record pointed by page_free_list and separate it
- Before returning, page_allog must nullify its pp_link field
- Also, if ALLOC_ZERO
*/
struct PageInfo *
page_alloc(int alloc_flags)
{
	if (page_free_list == NULL) {
        return NULL;
    }
    
    struct PageInfo *free_page = page_free_list;
    
    // remove it from the free list
    page_free_list = free_page->pp_link;
    
    // set pp_link to NULL
    free_page->pp_link = NULL;
    
    // zero the page if requested
    if (alloc_flags & ALLOC_ZERO) {
        memset(page2kva(free_page), 0, PGSIZE);
    }
    
    return free_page;
}

//
// Return a page to the free list.
// (This function should only be called when pp->pp_ref reaches 0.)
//
/*
- opposite of page_alloc()
- receive a 'struct PageInfo' record and put it back onto the list
- only done if pp_ref field on that page is zero and not linked to any other list with pp_link
- If either of these not true, panic
*/
void
page_free(struct PageInfo *pp)
{
	if (pp->pp_ref != 0) {
        panic("page_free: pp->pp_ref is nonzero");
    }
    if (pp->pp_link != NULL) {
        panic("page_free: pp->pp_link is not NULL");
    }
    
    pp->pp_link = page_free_list;
    page_free_list = pp;  
}

//
// Decrement the reference count on a page,
// freeing it if there are no more refs.
//
void
page_decref(struct PageInfo* pp)
{
	if (--pp->pp_ref == 0)
		page_free(pp);
}

/*
- receives a pointer to pml4e, a virtual address, and int create
- Obtain pointer to a record in pml4 table with: pml4e_t *pml4_re = &pml4e[PML4X(va)];
- Check if pointer is valid: if (*pml4_re & PTE_P) ...
- If valid, get pointer to PDPT table: pdpe_t *pdpe = KADDR(PTE_ADDR(*pml4_re));
- Ends with return pdpe_walk(pdpe, va, create); to pass onto next level
- If pointer pml4_re is not valid return NULL: if (!(*pml4_re & PTE_P)) return NULL;
     - BUT if createe != 0, call page_alloc to get a free page
	 - struct PageInfo *pp_page_table = page_alloc(ALLOC_ZERO);
	 - if pp_page_table is not null, increment its ref count
	 - Store the physical address with all permissions in PML4 table:
	   *pml4_re = page2pa(pp_page_table) | PTE_P | PTE_W | PTE_U;
	 - Complete link to PDPT table with: pdpe_t *pdpe = KADDR(PTE_ADDR(*pml4_re));
	 - return pdpe_walk(pdpe, va, create);
*/
pte_t *
pml4e_walk(pml4e_t *pml4e, const void *va, int create)
{
    pml4e_t *pml4_entry = &pml4e[PML4X(va)];
    pdpe_t *pdpe;
    
    if (!(*pml4_entry & PTE_P)) {
        if (! create) {
            return NULL;
        }
        
        struct PageInfo *pp = page_alloc(ALLOC_ZERO);
        if (pp == NULL) {
            return NULL;
        }
        
        pp->pp_ref++;
        *pml4_entry = page2pa(pp) | PTE_P | PTE_W | PTE_U;
    }
    
    pdpe = (pdpe_t *)KADDR(PTE_ADDR(*pml4_entry));
    return pdpe_walk(pdpe, va, create);
}

/*
Logic is the same with a couple changes:
- PML4 table is now PDPT (pdpe_t *pdpe)
- Old PDPT table is now Page Directory (pde_t *pgdir)
- Pointer to pml4 table (pml4e_t *pml4e) is now pointer to PDPT table (pdpe_t *pdpe)
- Macro is now PDPX(va) instead of PML4X(va)
- At the end, return pgdir_walk(pgdir, va, create);
*/
pte_t *
pdpe_walk(pdpe_t *pdpe,const void *va,int create)
{
    pdpe_t *pdpe_entry = &pdpe[PDPX(va)];
    pde_t *pgdir;
    
    if (!(*pdpe_entry & PTE_P)) {
        if (! create) {
            return NULL;
        }
        
        struct PageInfo *pp = page_alloc(ALLOC_ZERO);
        if (pp == NULL) {
            return NULL;
        }
        
        pp->pp_ref++;
        *pdpe_entry = page2pa(pp) | PTE_P | PTE_W | PTE_U;
    }
    
    pgdir = (pde_t *)KADDR(PTE_ADDR(*pdpe_entry));
    return pgdir_walk(pgdir, va, create);
}

/*
- Logic is the same with same changes pretty much
- Macro is now PDX(va)
- Should finally return the physical address:
  return &page_table[PTX(va)];
*/
pte_t *
pgdir_walk(pde_t *pgdir, const void *va, int create)
{
	pde_t *pde = &pgdir[PDX(va)];
    pte_t *page_table;
    
    if (!(*pde & PTE_P)) {
        if (! create) {
            return NULL;
        }
        
        struct PageInfo *pp = page_alloc(ALLOC_ZERO);
        if (pp == NULL) {
            return NULL;
        }
        
        pp->pp_ref++;
        *pde = page2pa(pp) | PTE_P | PTE_W | PTE_U;
    }
    
    page_table = (pte_t *)KADDR(PTE_ADDR(*pde));
    return &page_table[PTX(va)];
}


/*
- Loop to visit virtual pages to be allocated
- Inside loop, map virtual pages (va) to (pa) by setting page table entries with:
  pte_t *pte = pml4e_walk((pml4e_t *) pml4e, va, 1);
  *pte = pa | perm | PTE_P;
- va and pa must move alone with each iteration of loop
- DON'T INC pp_ref
*/
static void
boot_map_region(pde_t *pml4e, uintptr_t va, size_t size, physaddr_t pa, int perm)
{
	size_t i;
    pte_t *pte;
    
    for (i = 0; i < size; i += PGSIZE) {
        pte = pml4e_walk((pml4e_t *)pml4e, (void *)(va + i), 1);
        
        if (pte == NULL) {
            panic("boot_map_region: pml4e_walk failed");
        }
        *pte = (pa + i) | perm | PTE_P;
    }
}


/*
- To get a page to map the va, call pml4e_walk():
  pte_t *pte = pml4e_walk((pml4e_t *) pml4e, va, 1);
- If pte is NULL, return -E_NO_MEM
- Otherwise, inc pp_ref
- If page referenced by *pte is valid (*pte&PTE_P), use:
  page_remove(pml4e, va); to remove existing mapping
- Assign: *pte = page2pa(pp) | perm | PTE_P; return 0;
*/
int
page_insert(pde_t *pml4e, struct PageInfo *pp, void *va, int perm)
{
	pte_t *pte = pml4e_walk((pml4e_t *)pml4e, va, 1);
    
    if (pte == NULL) {
        return -E_NO_MEM;
    }

    pp->pp_ref++;
    
    if (*pte & PTE_P) {
        page_remove(pml4e, va);
    }
    
    *pte = page2pa(pp) | perm | PTE_P;
    
    return 0;
}


/*
- Get a value for the pointer to a page table record with pml4e_walk
  pte_t *pte = pml4e_walk((pml4e_t *) pml4e, va, 0);
- If the value is valid and not NULL, save in cal back var to be returned
  *pte_store = p_pte;
- AND return the struct PageInfo record corresponding to the pa in the PTE:
  return pa2page(PTE_ADDR(*p_pte));
- Otherwise return NULL
*/
struct PageInfo *
page_lookup(pde_t *pml4e, void *va, pte_t **pte_store)
{
	pte_t *pte = pml4e_walk((pml4e_t *)pml4e, va, 0);
    
    if (pte == NULL || ! (*pte & PTE_P)) {
        return NULL;
    }
    
    if (pte_store != NULL) {
        *pte_store = pte;
    }
    
    return pa2page(PTE_ADDR(*pte));
}


//
// Unmaps the physical page at virtual address 'va'.
// If there is no physical page at that address, silently does nothing.
//
// Details:
//   - The ref count on the physical page should decrement.
//   - The physical page should be freed if the refcount reaches 0.
//   - The pg table entry corresponding to 'va' should be set to 0.
//     (if such a PTE exists)
//   - The TLB must be invalidated if you remove an entry from
//     the page table.
//
// Hint: The TA solution is implemented using page_lookup,
// 	tlb_invalidate, and page_decref.
//
/*
- Call page_lookup to verify and locate the page of the va
  pte_t *pte = NULL;
  struct PageInfo *pp = page_lookup(pml4e, va, &pte);
- If pp is not NULL:
  *p_pte = 0; to zero out page
  page_decref(pp); decrements the pp_ref field
  tlb_invalidate(pml4e, va); invalidates the page in TLB
*/
void
page_remove(pde_t *pml4e, void *va)
{
	pte_t *pte = NULL;
    struct PageInfo *pp = page_lookup(pml4e, va, &pte);
    
    if (pp == NULL) {
        return;
    }
    
    *pte = 0;
    page_decref(pp);
    tlb_invalidate(pml4e, va);
}

//
// Invalidate a TLB entry, but only if the page tables being
// edited are the ones currently in use by the processor.
//
void
tlb_invalidate(pde_t *pml4e, void *va)
{
	// Flush the entry only if we're modifying the current address space.
	// For now, there is only one address space, so always invalidate.
	invlpg(va);
}


// --------------------------------------------------------------
// Checking functions.
// --------------------------------------------------------------

static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_kern_pml4e(void);
static physaddr_t check_va2pa(pml4e_t *pml4e, uintptr_t va);
static void check_page(void);
static void check_page_installed_pml4e(void);

#include <kern/pmaptests.h>
